name: ci
on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  jobs:
    test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      REPO: queue-master
    steps:
    - uses: actions/checkout@v2

       
    # Build
    - name: Build jar files
      run: ./scripts/build.sh

    
    # Unit test
    - name: Run unit tests
      run: ./test/test.sh unit.py

      
    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "gunareddy7" --password-stdin
    
    # Push to dockerhub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        path: docker/queue-master
        dockerfile: docker/queue-master/Dockerfile
