name: ci
on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      REPO: queue-master
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
      
    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml

    - name: Unit Tests
      run: mvn -q test
    
    # Build
    - name: Build jar files
      run: ./scripts/build.sh

    
    # Unit test
    - name: Run unit tests
      run: ./test/test.sh unit.py
      
  # Build docker image for service
    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        dockerfile: ./Dockerfile
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
    
    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "gunareddy7" --password-stdin
    
    # Push to dockerhub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        dockerfile: docker/queue-master/Dockerfile
        path: target/
        registry: docker.io
        image: gunareddy7/queue-master
        #tag_with_ref: true
        #tag_with_sha: true
        
        
